# Generated by Django 3.2 on 2023-01-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_auto_20230118_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_timer',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
