# Generated by Django 3.2 on 2023-01-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_alter_user_access_timer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='acccess_counter',
            new_name='access_counter',
        ),
    ]
