# Generated by Django 3.2 on 2023-01-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_rename_acccess_counter_user_access_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_timer',
            field=models.DateTimeField(),
        ),
    ]
